docs: change readme text
zitadel/.github pull request #3
Opened 2022-10-13 08:41 UTC by fforootd

2022-10-13 09:59 UTC, hifabienne approved these changes

2022-10-14 14:56 UTC, hifabienne approved these changes

2022-10-14 16:23 UTC, eliobischof requested changes
Markdown files are easier maintainable when lines are split, because git splits changes by lines too. It does not change the rendered HTML.

2022-10-14 16:23 UTC, eliobischof commented on profile/README.md
> +Prior of starting ZITADEL the founders worked for a public sector company, where we built and operated a complex service provider grade identity system. This helped the company to provide IT services
```suggestion
Prior of starting ZITADEL the founders worked for a public sector company,
where they built and operated a complex service provider grade identity system.
This helped the company to provide IT services to government entities, first responders and citizens alike.
```

2022-10-14 16:23 UTC, eliobischof commented on profile/README.md
> +ZITADEL is the best open source alternative for Auth0 and Keycloak. It provides all the needed security features without a paywall, is built for the serverless era and brings along a unique multi ten
```suggestion
ZITADEL is the best open source alternative for Auth0 and Keycloak.
It provides all the needed security features without a paywall,
is built for the serverless era and brings along a unique multi tenancy concept with self-service for your b2b needs.
```

2022-10-17 08:06 UTC, eliobischof approved these changes

2022-10-17 08:07 UTC, merged